#!/usr/bin/env bash
# Helpers sourced by entrypoint.sh. Expects: CLUSTER_NAME CLUSTER_DIR KLEI_DIR
# DST_DIR CTL_DIR BACKUP_DIR LOCAL_MODS_DIR, arrays SHARDS SHARD_FD SHARD_PID.

log() { printf '[dst-server %s] %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; }

# cluster.ini plus at least one <shard>/server.ini.
cluster_ready() {
  [[ -f "$CLUSTER_DIR/cluster.ini" ]] || return 1
  local f
  for f in "$CLUSTER_DIR"/*/server.ini; do [[ -f "$f" ]] && return 0; done
  return 1
}

# Prints shard dir names, master first (is_master = true in server.ini).
discover_shards() {
  local f d master="" others=()
  for f in "$CLUSTER_DIR"/*/server.ini; do
    [[ -f "$f" ]] || continue
    d="$(basename "$(dirname "$f")")"
    if grep -qiE '^\s*is_master\s*=\s*true' "$f"; then master="$d"; else others+=("$d"); fi
  done
  [[ -n "$master" ]] && echo "$master"
  local o
  for o in "${others[@]}"; do echo "$o"; done
}

write_cluster_token() {
  local tok="$CLUSTER_DIR/cluster_token.txt"
  if [[ -s "$tok" ]]; then return 0; fi
  if [[ -z "${CLUSTER_TOKEN:-}" ]]; then
    log "WARNING: no cluster_token.txt and CLUSTER_TOKEN is empty — players cannot join"
    return 0
  fi
  (umask 077 && printf '%s' "$CLUSTER_TOKEN" > "$tok")
  log "wrote cluster_token.txt from CLUSTER_TOKEN"
}

# dedicated_server_mods_setup.lua is derived from every workshop-<id> in the
# cluster's modoverrides.lua files, so operators only edit modoverrides.
sync_mods() {
  local setup="$DST_DIR/mods/dedicated_server_mods_setup.lua" f ids=() d name
  mkdir -p "$DST_DIR/mods"
  local overrides=()
  for f in "$CLUSTER_DIR"/*/modoverrides.lua; do [[ -f "$f" ]] && overrides+=("$f"); done
  if (( ${#overrides[@]} )); then
    mapfile -t ids < <(grep -hoE 'workshop-[0-9]+' "${overrides[@]}" | sed 's/workshop-//' | sort -u)
  fi
  {
    echo "-- generated by dst-server entrypoint $(date -u +%FT%TZ); edit <shard>/modoverrides.lua instead"
    for name in "${ids[@]}"; do echo "ServerModSetup(\"$name\")"; done
  } > "$setup"
  log "workshop mods requested: ${#ids[@]}"
  for d in "$LOCAL_MODS_DIR"/*/; do
    [[ -f "$d/modinfo.lua" ]] || continue
    name="$(basename "$d")"
    rm -rf "${DST_DIR:?}/mods/$name"
    cp -r "$d" "$DST_DIR/mods/$name"
    log "local mod synced: $name"
  done
}

# Write one console line to a shard through the fd we hold on its FIFO.
send_cmd() {
  local shard="$1" line="$2"
  printf '%s\n' "$line" >&"${SHARD_FD[$shard]}"
}

shard_alive() { kill -0 "${SHARD_PID[$1]}" 2>/dev/null; }

# Wait up to $2 seconds for shard $1 to exit, then TERM, then KILL.
wait_exit_or_kill() {
  local shard="$1" deadline="$2" i
  for (( i = 0; i < deadline; i++ )); do
    shard_alive "$shard" || return 0
    sleep 1
  done
  log "$shard did not exit within ${deadline}s — SIGTERM"
  kill -TERM "${SHARD_PID[$shard]}" 2>/dev/null || true
  sleep 5
  if shard_alive "$shard"; then
    log "$shard still alive — SIGKILL"
    kill -KILL "${SHARD_PID[$shard]}" 2>/dev/null || true
  fi
}

# c_save() everywhere, then c_shutdown(true) everywhere, then wait.
stop_all_shards() {
  local s
  for s in "${SHARDS[@]}"; do shard_alive "$s" && { log "$s: c_save()"; send_cmd "$s" "c_save()"; }; done
  sleep 3
  for s in "${SHARDS[@]}"; do shard_alive "$s" && { log "$s: c_shutdown(true)"; send_cmd "$s" "c_shutdown(true)"; }; done
  for s in "${SHARDS[@]}"; do wait_exit_or_kill "$s" 60; done
}

# Local zip after the shards are down. Day comes from dst-saves' state.json.
write_stop_zip() {
  [[ -f "$CLUSTER_DIR/cluster.ini" ]] || return 0
  local day="" ts name
  if [[ -f "$CTL_DIR/state.json" ]]; then
    day="$(sed -nE 's/.*"cycles": *([0-9]+).*/\1/p' "$CTL_DIR/state.json" | head -1)"
  fi
  ts="$(date -u +%Y%m%dT%H%M%SZ)"
  if [[ -n "$day" ]]; then name="${ts}_day$(printf '%04d' "$day")_stop.zip"; else name="${ts}_stop.zip"; fi
  ( cd "$KLEI_DIR/DoNotStarveTogether" \
    && zip -qrX "$BACKUP_DIR/$name" "$CLUSTER_NAME" -x '*/backup/*' '*.DS_Store' '__MACOSX/*' )
  log "stop zip written: $name"
}
